### ISSUE TITLE
Different file priority for sync and async version

### ISSUE THREAD

**Issue by IlCallo** [tleunen/find-babel-config#33]
Maybe I'm not understanding it well, but seems to me that the script stops to the first configuration it finds.

But while looking at the code, I noticed that async and sync version have a different research order.

Async:  .babelrc, .babelrc.js, package.json, babel.config.js
Sync:  .babelrc, .babelrc.js, babel.config.js, package.json

**Comment by tleunen** [comment]
You're right, and the order should be the same for both ways. I'm going to fix that

**Comment by IlCallo** [comment]
Thank you!
