### ISSUE TITLE
Create a release to release updated dependencies

### ISSUE THREAD

**Issue by wejendorp** [tleunen/find-babel-config#59]
As part of the https://github.com/tleunen/babel-plugin-module-resolver/ dependencies, it'd be great to get the `json5` bump out.

This will allow using module-resolver without introducing https://security.snyk.io/package/npm/json5/2.2.1

Is it possible to create a release from master?

**Comment by enahum** [comment]
looking fwd to the release and then upgrade module-resolver ;)

**Comment by Gowtham-Enlume** [comment]
@tleunen, as @wejendorp mentioned above, could you please make a new release from the master so that it would resolve to the latest `json5: 2.2.2`, which fixes the vulnerability. Thank you

**Comment by karlhorky** [comment]
Also reported in `babel-plugin-module-resolver` over here:

- https://github.com/tleunen/babel-plugin-module-resolver/issues/439

**Comment by Gowtham-Enlume** [comment]
Hi folks, I just reached out to @tleunen by mail. The release can be expected by about next Monday as he is out of town and unavailability with the laptop.

**Comment by tleunen** [comment]
Version 2.0.0 published
