### ISSUE TITLE
Vulnerable json5@0.5.1 is part of find-babel-config

### ISSUE THREAD

**Issue by severus1990** [tleunen/find-babel-config#60]
The latest version of find-babel-config 1.2.0, is having a vulnerable version of json5 **(json5@0.5.1)**

Will there be any fixes for this?

**Comment by felix-gohla** [comment]
Duplicate of #59. See the following comment: <https://github.com/tleunen/find-babel-config/issues/59#issuecomment-1369953238>

**Comment by severus1990** [comment]
Thank you! @felix-gohla

**Comment by felix-gohla** [comment]
Could you close this issue, then? 😊

**Comment by tleunen** [comment]
Duplicate of #59
