### ISSUE TITLE
Vulnerable version of json5 used in 1.x version of this package

### ISSUE THREAD

**Issue by LucasHillDex** [tleunen/find-babel-config#70]
@tleunen Over 50% of downloads of this package are still using 1.2.0 unfortunately. Json5 was patched in the 2.0 release, but given the wide use of the library, I think release a patch version of 1.2.1 to fix the vulnerability would be worth it! See my PR based on 1.2.0:

https://github.com/tleunen/find-babel-config/pull/69

**Comment by tleunen** [comment]
Isn't it a good reason for people to migrate to v2?

I'll try to release a new v1 version with that update later today. Thanks for the heads up

**Comment by LucasHillDex** [comment]
> Isn't it a good reason for people to migrate to v2?

Absolutely! Unfortunately with the wide use of the library, and many packages being defunct etc, it can be quite difficult to get traction on getting it out of your dependency tree. In my opinion that makes critical vulnerabilities like this worth patching in old versions (especially when there's no breaking API changes etc) but I understand the tradeoffs.

**Comment by LucasHill** [comment]
@tleunen I had to re-open the PR under a different user, let me know if you were still thinking of doing a release, thanks!
https://github.com/tleunen/find-babel-config/pull/71

**Comment by tleunen** [comment]
@LucasHill If I did it right, the package should now be updated. :) Sorry for the wait. It's been a while since I touched this

**Comment by LucasHill** [comment]
@tleunen everything is looking great on my end! Thanks so much!

**Comment by ljharb** [comment]
@tleunen unfortunately, json5 v2 requires node 6, and v1 of find-babel-config supports node 4, so this was a breaking change (and breaks eslint-plugin-import) - can you please publish a v1.2.2 of find-babel-config that reverts to v0 or v1 of json5?

**Comment by LucasHill** [comment]
@ljharb @tleunen version 1.0.2 of JSON5 is patched so that would still avoid the vulnerability if it is compatible with node4.

**Comment by tleunen** [comment]
Oh... Good catch! Let me fix that and publish 1.2.2 real quick. Thank you both!

**Comment by ljharb** [comment]
Thank you!
