### ISSUE TITLE
Breaking Change Introduced in Minor Version Update from 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by jinliming2** [tleunen/find-babel-config#75]
Raising the minimum required Node.js version to 18 constitutes a breaking change, yet it was introduced in a minor version update.
This has resulted in `babel-plugin-module-resolver@5.0.0` becoming non-functional under Node.js 16, as it depends on this package's `^2.0.0` version, which now installs the `2.1.0` version with the breaking change.

**Comment by tleunen** [comment]
@jinliming2 You're right. Sorry about that. #76 should fix this and I'm releasing 2.1.1
